// Placeholder generated by `flutter create` — replaced with a no-op import
// check so the file compiles without referencing the stale `MyApp` class that
// the template generates.  The playground's real tests live in test/**.dart.
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('placeholder', (WidgetTester tester) async {
    // No-op: the playground app requires platform channels (file_selector,
    // printing) that cannot run headless in the widget test harness.
  });
}
