// GENERATED by tool/fetch_google_fonts.dart — do not edit by hand.
//
// The bundled catalog: one entry per family, each with the asset key of every
// present face. Asset keys are package-prefixed so they resolve for consumers
// and in this package's own tests.
library;

import 'package:jet_print/jet_print.dart' show JetFontWeight;

import 'google_font_entry.dart';

const String _base = 'packages/jet_print_google_fonts/assets/fonts';

/// Every family bundled with this package, in catalog order.
const List<GoogleFontEntry> googleFontCatalog = <GoogleFontEntry>[
  GoogleFontEntry(
    name: 'Noto Sans',
    license: 'OFL-1.1',
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Noto Sans/NotoSans-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Noto Sans/NotoSans-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Noto Sans/NotoSans-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Noto Sans/NotoSans-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Noto Serif',
    license: 'OFL-1.1',
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Noto Serif/NotoSerif-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Noto Serif/NotoSerif-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Noto Serif/NotoSerif-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Noto Serif/NotoSerif-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'JetBrains Mono',
    license: 'OFL-1.1',
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/JetBrains Mono/JetBrainsMono-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/JetBrains Mono/JetBrainsMono-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/JetBrains Mono/JetBrainsMono-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/JetBrains Mono/JetBrainsMono-BoldItalic.ttf',
    },
  ),
];
