// GENERATED by tool/fetch_google_fonts.dart — do not edit by hand.
library;

import 'package:jet_print/jet_print.dart' show JetFontWeight;

import 'google_font_entry.dart';

const String _base = 'packages/jet_print_google_fonts/assets/fonts';

/// Every family bundled with this package, in catalog order.
const List<GoogleFontEntry> googleFontCatalog = <GoogleFontEntry>[
  GoogleFontEntry(
    name: 'Arvo',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Arvo/Arvo-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false): '$_base/Arvo/Arvo-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Arvo/Arvo-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Arvo/Arvo-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Barlow',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Barlow/Barlow-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Barlow/Barlow-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Barlow/Barlow-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Barlow/Barlow-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Bitter',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Bitter/Bitter-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Bitter/Bitter-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Bitter/Bitter-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Bitter/Bitter-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Cabin',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Cabin/Cabin-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Cabin/Cabin-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Cabin/Cabin-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Cabin/Cabin-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Crimson Text',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Crimson Text/CrimsonText-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Crimson Text/CrimsonText-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Crimson Text/CrimsonText-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Crimson Text/CrimsonText-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'DM Sans',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/DM Sans/DMSans-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/DM Sans/DMSans-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/DM Sans/DMSans-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/DM Sans/DMSans-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'EB Garamond',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/EB Garamond/EBGaramond-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/EB Garamond/EBGaramond-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/EB Garamond/EBGaramond-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/EB Garamond/EBGaramond-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Fira Sans',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Fira Sans/FiraSans-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Fira Sans/FiraSans-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Fira Sans/FiraSans-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Fira Sans/FiraSans-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Inter',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Inter/Inter-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Inter/Inter-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Inter/Inter-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Inter/Inter-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'JetBrains Mono',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/JetBrains Mono/JetBrainsMono-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/JetBrains Mono/JetBrainsMono-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/JetBrains Mono/JetBrainsMono-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/JetBrains Mono/JetBrainsMono-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Karla',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Karla/Karla-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Karla/Karla-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Karla/Karla-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Karla/Karla-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Lato',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Lato/Lato-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false): '$_base/Lato/Lato-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Lato/Lato-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Lato/Lato-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Libre Baskerville',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Libre Baskerville/LibreBaskerville-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Libre Baskerville/LibreBaskerville-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Libre Baskerville/LibreBaskerville-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Libre Baskerville/LibreBaskerville-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Libre Franklin',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Libre Franklin/LibreFranklin-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Libre Franklin/LibreFranklin-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Libre Franklin/LibreFranklin-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Libre Franklin/LibreFranklin-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Lora',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Lora/Lora-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false): '$_base/Lora/Lora-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Lora/Lora-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Lora/Lora-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Manrope',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Manrope/Manrope-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Manrope/Manrope-Bold.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Merriweather',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Merriweather/Merriweather-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Merriweather/Merriweather-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Merriweather/Merriweather-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Merriweather/Merriweather-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Montserrat',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Montserrat/Montserrat-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Montserrat/Montserrat-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Montserrat/Montserrat-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Montserrat/Montserrat-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Mulish',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Mulish/Mulish-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Mulish/Mulish-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Mulish/Mulish-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Mulish/Mulish-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Noto Sans',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Noto Sans/NotoSans-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Noto Sans/NotoSans-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Noto Sans/NotoSans-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Noto Sans/NotoSans-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Noto Serif',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Noto Serif/NotoSerif-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Noto Serif/NotoSerif-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Noto Serif/NotoSerif-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Noto Serif/NotoSerif-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Nunito',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Nunito/Nunito-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Nunito/Nunito-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Nunito/Nunito-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Nunito/Nunito-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Open Sans',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Open Sans/OpenSans-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Open Sans/OpenSans-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Open Sans/OpenSans-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Open Sans/OpenSans-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'PT Serif',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/PT Serif/PTSerif-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/PT Serif/PTSerif-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/PT Serif/PTSerif-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/PT Serif/PTSerif-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Playfair Display',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Playfair Display/PlayfairDisplay-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Playfair Display/PlayfairDisplay-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Playfair Display/PlayfairDisplay-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Playfair Display/PlayfairDisplay-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Poppins',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Poppins/Poppins-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Poppins/Poppins-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Poppins/Poppins-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Poppins/Poppins-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Raleway',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Raleway/Raleway-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Raleway/Raleway-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Raleway/Raleway-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Raleway/Raleway-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Roboto',
    license: 'Apache-2.0', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Roboto/Roboto-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Roboto/Roboto-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Roboto/Roboto-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Roboto/Roboto-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Roboto Slab',
    license: 'Apache-2.0', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Roboto Slab/RobotoSlab-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Roboto Slab/RobotoSlab-Bold.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Rubik',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Rubik/Rubik-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Rubik/Rubik-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Rubik/Rubik-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Rubik/Rubik-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Source Sans 3',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Source Sans 3/SourceSans3-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Source Sans 3/SourceSans3-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Source Sans 3/SourceSans3-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Source Sans 3/SourceSans3-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Spectral',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Spectral/Spectral-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Spectral/Spectral-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Spectral/Spectral-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Spectral/Spectral-BoldItalic.ttf',
    },
  ),
  GoogleFontEntry(
    name: 'Work Sans',
    license: 'OFL-1.1', // maintainer: verify per family
    faceAssets: <FontFaceSlot, String>{
      (weight: JetFontWeight.normal, italic: false):
          '$_base/Work Sans/WorkSans-Regular.ttf',
      (weight: JetFontWeight.bold, italic: false):
          '$_base/Work Sans/WorkSans-Bold.ttf',
      (weight: JetFontWeight.normal, italic: true):
          '$_base/Work Sans/WorkSans-Italic.ttf',
      (weight: JetFontWeight.bold, italic: true):
          '$_base/Work Sans/WorkSans-BoldItalic.ttf',
    },
  ),
];
