// Regenerates `lib/src/rendering/text/fonts/default_font_data.dart` from the
// committed subset TTFs. Run from the package root:
//
//   dart run tool/generate_default_font.dart
//
// The source fonts under `tool/fonts/` are Latin subsets, all under the SIL
// Open Font License 1.1 (see `lib/src/rendering/text/fonts/OFL.txt`) and all
// covering the identical codepoint set (U+0020-007E, U+00A0-017F,
// U+2010-2014, U+2018-2022, U+2026, U+20AC, U+2122):
//
//   * JetSans  — Noto Sans (Regular / Bold / Italic / Bold Italic)
//   * JetSerif — Noto Serif (same four faces)
//   * JetMono  — JetBrains Mono (same four faces; layout features stripped)
//
// They are embedded as base64 so the headless TextMeasurer and every paint
// backend resolve the same font bytes from one source, with no
// asset/rootBundle dependency.
import 'dart:convert';
import 'dart:io';

/// (source TTF, emitted top-level identifier, face description) per variant.
const List<(String, String, String)> _faces = <(String, String, String)>[
  ('NotoSans-subset.ttf', 'kDefaultFontBytes', 'JetSans Regular'),
  ('NotoSans-Bold-subset.ttf', 'kDefaultFontBoldBytes', 'JetSans Bold'),
  ('NotoSans-Italic-subset.ttf', 'kDefaultFontItalicBytes', 'JetSans Italic'),
  (
    'NotoSans-BoldItalic-subset.ttf',
    'kDefaultFontBoldItalicBytes',
    'JetSans Bold Italic'
  ),
  ('NotoSerif-Regular-subset.ttf', 'kSerifFontBytes', 'JetSerif Regular'),
  ('NotoSerif-Bold-subset.ttf', 'kSerifFontBoldBytes', 'JetSerif Bold'),
  ('NotoSerif-Italic-subset.ttf', 'kSerifFontItalicBytes', 'JetSerif Italic'),
  (
    'NotoSerif-BoldItalic-subset.ttf',
    'kSerifFontBoldItalicBytes',
    'JetSerif Bold Italic'
  ),
  ('JetBrainsMono-Regular-subset.ttf', 'kMonoFontBytes', 'JetMono Regular'),
  ('JetBrainsMono-Bold-subset.ttf', 'kMonoFontBoldBytes', 'JetMono Bold'),
  ('JetBrainsMono-Italic-subset.ttf', 'kMonoFontItalicBytes', 'JetMono Italic'),
  (
    'JetBrainsMono-BoldItalic-subset.ttf',
    'kMonoFontBoldItalicBytes',
    'JetMono Bold Italic'
  ),
];

void main() {
  final StringBuffer out = StringBuffer('''
// GENERATED by tool/generate_default_font.dart — do not edit by hand.
//
// Embedded bytes of the bundled fonts — JetSans (Noto Sans), JetSerif
// (Noto Serif), and JetMono (JetBrains Mono), each in Regular, Bold, Italic,
// and Bold Italic faces — as a Latin subset (Basic Latin, Latin-1 Supplement,
// Latin Extended-A, and common typographic punctuation). All are licensed
// under the SIL Open Font License 1.1 — see OFL.txt. Embedding keeps every
// face available to the headless TextMeasurer and to paint backends from one
// source, with no asset/rootBundle dependency — so a family or Bold/Italic
// edit renders identically on canvas, preview, and export (Constitution IV).
library;

import 'dart:convert';
import 'dart:typed_data';
''');

  for (final (String file, String identifier, String face) in _faces) {
    final File ttf = File('tool/fonts/$file');
    if (!ttf.existsSync()) {
      stderr.writeln('Missing ${ttf.path}; run from the package root.');
      exitCode = 1;
      return;
    }
    final List<int> bytes = ttf.readAsBytesSync();
    final String b64 = base64Encode(bytes);

    final StringBuffer chunks = StringBuffer();
    const int width = 100;
    for (int i = 0; i < b64.length; i += width) {
      final int end = (i + width < b64.length) ? i + width : b64.length;
      chunks.writeln("    '${b64.substring(i, end)}'");
    }

    final String b64Name = '_b64${identifier.substring(1)}';
    out.write('''

/// Raw bytes of the bundled $face face (decoded once at first access).
final Uint8List $identifier = base64Decode($b64Name);

const String $b64Name =
${chunks.toString().trimRight()};
''');
    stdout.writeln('$file -> $identifier (${bytes.length} font bytes).');
  }

  File('lib/src/rendering/text/fonts/default_font_data.dart')
      .writeAsStringSync(out.toString());
  // NB: total embedded payload is reported per face above; keep an eye on it
  // when adding families — every consumer of the library carries these bytes.
  stdout.writeln('Wrote default_font_data.dart.');
}
