// Regenerates `lib/src/rendering/text/fonts/default_font_data.dart` from the
// committed subset TTFs. Run from the package root:
//
//   dart run tool/generate_default_font.dart
//
// The source fonts (`tool/fonts/NotoSans-subset.ttf` and its Bold / Italic /
// BoldItalic siblings) are Latin subsets of Noto Sans under the SIL Open Font
// License 1.1 (see `lib/src/rendering/text/fonts/OFL.txt`), all covering the
// identical codepoint set (U+0020-007E, U+00A0-017F, U+2010-2014,
// U+2018-2022, U+2026, U+20AC, U+2122). They are embedded as base64 so the
// headless TextMeasurer and every paint backend resolve the same font bytes
// from one source, with no asset/rootBundle dependency.
import 'dart:convert';
import 'dart:io';

/// (source TTF, emitted top-level identifier, face description) per variant.
const List<(String, String, String)> _faces = <(String, String, String)>[
  ('NotoSans-subset.ttf', 'kDefaultFontBytes', 'Regular'),
  ('NotoSans-Bold-subset.ttf', 'kDefaultFontBoldBytes', 'Bold'),
  ('NotoSans-Italic-subset.ttf', 'kDefaultFontItalicBytes', 'Italic'),
  (
    'NotoSans-BoldItalic-subset.ttf',
    'kDefaultFontBoldItalicBytes',
    'Bold Italic'
  ),
];

void main() {
  final StringBuffer out = StringBuffer('''
// GENERATED by tool/generate_default_font.dart — do not edit by hand.
//
// Embedded bytes of the bundled default font: Noto Sans (Regular, Bold,
// Italic, Bold Italic), Latin subset (Basic Latin, Latin-1 Supplement, Latin
// Extended-A, and common typographic punctuation). Licensed under the SIL
// Open Font License 1.1 — see OFL.txt. Embedding keeps every face available
// to the headless TextMeasurer and to paint backends from one source, with no
// asset/rootBundle dependency — so a Bold/Italic edit renders identically on
// canvas, preview, and export (Constitution IV).
library;

import 'dart:convert';
import 'dart:typed_data';
''');

  for (final (String file, String identifier, String face) in _faces) {
    final File ttf = File('tool/fonts/$file');
    if (!ttf.existsSync()) {
      stderr.writeln('Missing ${ttf.path}; run from the package root.');
      exitCode = 1;
      return;
    }
    final List<int> bytes = ttf.readAsBytesSync();
    final String b64 = base64Encode(bytes);

    final StringBuffer chunks = StringBuffer();
    const int width = 100;
    for (int i = 0; i < b64.length; i += width) {
      final int end = (i + width < b64.length) ? i + width : b64.length;
      chunks.writeln("    '${b64.substring(i, end)}'");
    }

    final String b64Name = '_b64${identifier.substring(1)}';
    out.write('''

/// Raw bytes of the bundled default font's $face face (decoded once at first
/// access).
final Uint8List $identifier = base64Decode($b64Name);

const String $b64Name =
${chunks.toString().trimRight()};
''');
    stdout.writeln('$file -> $identifier (${bytes.length} font bytes).');
  }

  File('lib/src/rendering/text/fonts/default_font_data.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('Wrote default_font_data.dart.');
}
