// Regenerates `lib/src/rendering/text/fonts/default_font_data.dart` from the
// committed subset TTF. Run from the package root:
//
//   dart run tool/generate_default_font.dart
//
// The source font (`tool/fonts/NotoSans-subset.ttf`) is a Latin subset of Noto
// Sans Regular under the SIL Open Font License 1.1 (see
// `lib/src/rendering/text/fonts/OFL.txt`). It is embedded as base64 so the
// headless TextMeasurer and every paint backend resolve the same font bytes from
// one source, with no asset/rootBundle dependency.
import 'dart:convert';
import 'dart:io';

void main() {
  final File ttf = File('tool/fonts/NotoSans-subset.ttf');
  if (!ttf.existsSync()) {
    stderr.writeln('Missing ${ttf.path}; run from the package root.');
    exitCode = 1;
    return;
  }
  final List<int> bytes = ttf.readAsBytesSync();
  final String b64 = base64Encode(bytes);

  final StringBuffer chunks = StringBuffer();
  const int width = 100;
  for (int i = 0; i < b64.length; i += width) {
    final int end = (i + width < b64.length) ? i + width : b64.length;
    chunks.writeln("    '${b64.substring(i, end)}'");
  }

  final String out = '''
// GENERATED by tool/generate_default_font.dart — do not edit by hand.
//
// Embedded bytes of the bundled default font: Noto Sans Regular, Latin subset
// (Basic Latin, Latin-1 Supplement, Latin Extended-A, and common typographic
// punctuation). Licensed under the SIL Open Font License 1.1 — see OFL.txt.
// Embedding keeps the font available to the headless TextMeasurer and to paint
// backends from one source, with no asset/rootBundle dependency.
library;

import 'dart:convert';
import 'dart:typed_data';

/// Raw bytes of the bundled default font (decoded once at first access).
final Uint8List kDefaultFontBytes = base64Decode(_b64);

const String _b64 =
${chunks.toString().trimRight()};
''';

  File('lib/src/rendering/text/fonts/default_font_data.dart')
      .writeAsStringSync(out);
  stdout.writeln('Wrote default_font_data.dart (${bytes.length} font bytes, '
      '${b64.length} base64 chars).');
}
