// Structural tests for PdfPainter watermark support (Task 8):
//   - rotation (pushTransform/popTransform) does not throw and produces bytes
//   - image opacity wraps draw in a graphics-state context and produces bytes
@TestOn('vm')
library;

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:jet_print/src/domain/elements/image_source.dart';
import 'package:jet_print/src/domain/geometry.dart';
import 'package:jet_print/src/domain/page_format.dart';
import 'package:jet_print/src/domain/styles/color.dart';
import 'package:jet_print/src/rendering/export/pdf_painter.dart';
import 'package:jet_print/src/rendering/frame/page_frame.dart';
import 'package:jet_print/src/rendering/frame/primitive.dart';
import 'package:jet_print/src/rendering/paint/report_painter.dart';
import 'package:jet_print/src/rendering/text/font_registry.dart';

const PageFormat _page =
    PageFormat(width: 100, height: 100, margins: JetEdgeInsets.all(0));

/// Valid 1x1 white RGB PNG (69 bytes, generated by Python zlib/struct).
final Uint8List _png1x1 = Uint8List.fromList(<int>[
  137, 80, 78, 71, 13, 10, 26, 10, // PNG signature
  0, 0, 0, 13, 73, 72, 68, 82, // IHDR chunk: length + type
  0, 0, 0, 1, 0, 0, 0, 1, 8, 2, 0, 0, 0, 144, 119, 83, 222, // 1x1 RGB8
  0, 0, 0, 12, 73, 68, 65, 84, // IDAT chunk: length + type
  120, 156, 99, 248, 255, 255, 63, 0, 5, 254, 2, 254, // IDAT zlib data
  13, 239, 70, 184, // IDAT crc
  0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130, // IEND chunk
]);

PdfPainter _painter() => PdfPainter(FontRegistry()..registerDefault());

void main() {
  test('paints a rotated rect to PDF without throwing', () async {
    final PageFrame frame = PageFrame(
      page: _page,
      primitives: <FramePrimitive>[
        const RectPrimitive(
          bounds: JetRect(x: 20, y: 20, width: 60, height: 20),
          fill: JetColor(0x26000000),
          rotation: -0.785,
        ),
      ],
    );
    final PdfPainter painter = _painter();
    await paintFrame(frame, painter);
    final Uint8List bytes = await painter.save();
    expect(bytes, isNotEmpty);
  });

  test('paints an image with opacity < 1.0 to PDF without throwing', () async {
    final PageFrame frame = PageFrame(
      page: _page,
      primitives: <FramePrimitive>[
        ImagePrimitive(
          bounds: const JetRect(x: 10, y: 10, width: 50, height: 50),
          bytes: _png1x1,
          fit: JetBoxFit.fill,
          opacity: 0.3,
        ),
      ],
    );
    final PdfPainter painter = _painter();
    await paintFrame(frame, painter);
    final Uint8List bytes = await painter.save();
    expect(bytes, isNotEmpty);
  });

  test('paints an image with opacity == 1.0 to PDF without throwing', () async {
    final PageFrame frame = PageFrame(
      page: _page,
      primitives: <FramePrimitive>[
        ImagePrimitive(
          bounds: const JetRect(x: 10, y: 10, width: 50, height: 50),
          bytes: _png1x1,
          fit: JetBoxFit.fill,
          opacity: 1.0,
        ),
      ],
    );
    final PdfPainter painter = _painter();
    await paintFrame(frame, painter);
    final Uint8List bytes = await painter.save();
    expect(bytes, isNotEmpty);
  });
}
